version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_username"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: